### ISSUE TITLE
There are no source files available in this repository

### ISSUE THREAD

**Issue by Xrayez** [VoiDjinn/vdautomata#1]
Did you forget to `git push`?

**Comment by VoiDjinn** [comment]
@Xrayez Hi there, 
and no, not at all.
At the moment i am still preparing the sources before i publish them, since i am not quite happy with the current state.

**Comment by Xrayez** [comment]
Yeah, I was just skimming through `godot-modules` topic on GitHub and stumbled upon your modules, to be honest I couldn't figure out the usefulness of those at first glance, you may consider provide some minimal overview/documentation for those as well. 😃

FYI, I'm maintaining a list of community modules I find at https://github.com/goostengine/godot-modules.

Happy coding!

**Comment by VoiDjinn** [comment]
@Xrayez Believe me, i am at that point at the very moment, especially looking forward to the part about documentation :stuck_out_tongue_closed_eyes:

But you are right, i should mark this repository at least as WIP for the moment, hopefully it won't stay that way so long :+1:

Knew about that list, but didn't recognized you as the author right away.
Maybe in the future my modules too have the honour to be on your list? :smiley:

Anyway, will close this issue then.
Happy coding to you as well!

**Comment by Xrayez** [comment]
> Maybe in the future my modules too have the honour to be on your list? 😃

Sure, not sure if it makes sense to impose some quality restrictions, the purpose of the modules repository is exactly so that people can judge the quality themselves. 🙂
